# - ssh auth
# - without sa
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: key-for-git
  namespace: tekton-demo
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSV...
  known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQ...
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-git3
  namespace: tekton-demo
spec:
  workspaces:
    - name: source
  steps:
    - name: git-checkout
      image: alpine/git
      env:
        - name: GIT_SSH_COMMAND
          value: ssh -i ~/.ssh/ssh-privatekey -o UserKnownHostsFile=/etc/secrets/known_hosts
      script: |
        #!/usr/bin/env sh
        mkdir -p ~/.ssh
        cp /etc/secrets/ssh-privatekey ~/.ssh/ssh-privatekey
        chmod 600 ~/.ssh/ssh-privatekey
        cd $(workspaces.source.path)
        git clone git@github.com:guobinqiu/hack.git .
      volumeMounts:
        - name: key-for-git
          mountPath: /etc/secrets
    - name: show-readme
      image: alpine
      script: |
        #!/usr/bin/env sh
        cat $(workspaces.source.path)/README.md
  volumes:
    - name: key-for-git
      secret:
        secretName: key-for-git
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-git3
  namespace: tekton-demo
spec:
  taskRef:
    name: task-git3
  workspaces:
    - name: source
      emptyDir: {}
