---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: key-for-git
  namespace: tekton-demo
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSV...
  known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQ...
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-service-account
  namespace: tekton-demo
secrets:
  - name: key-for-git
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-git1
  namespace: tekton-demo
spec:
  workspaces:
    - name: source
  steps:
    - name: git-checkout
      image: alpine/git
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.source.path)
        git clone git@github.com:guobinqiu/hack.git .
    - name: show-readme
      image: alpine
      script: |
        #!/usr/bin/env sh
        cat $(workspaces.source.path)/README.md
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-git1
  namespace: tekton-demo
spec:
  serviceAccountName: git-service-account
  taskRef:
    name: task-git1
  workspaces:
    - name: source
      emptyDir: {}
