---
apiVersion: v1
kind: Secret
metadata:
  name: key-for-docker
  namespace: tekton-demo
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: qiuguobin
  password: dckr_pat_DamamBGkd3L...
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-docker5
  namespace: tekton-demo
spec:
  params:
    - name: username
      type: string
    - name: password
      type: string
  sidecars:
    - name: docker-dind
      image: docker:dind
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: tcp://0.0.0.0:2375
      securityContext:
        privileged: true
  steps:
    - name: docker-checkout
      image: docker
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      script: |
        #!/usr/bin/env sh
        mkdir -p ~/.docker
        DOCKER_REGISTRY=https://index.docker.io/v1/
        AUTH_VALUE=$(echo -n "$(params.username):$(params.password)" | base64)
        cat <<EOF > ~/.docker/config.json
        {
          "auths": {
            "$DOCKER_REGISTRY": {
              "auth": "$AUTH_VALUE"
            }
          }
        }
        EOF
        chmod 600 ~/.docker/config.json
        cat ~/.docker/config.json
        while ! docker info; do sleep 1; done
        docker pull qiuguobin/hellogo
        docker images
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-docker5
  namespace: tekton-demo
spec:
  params:
    - name: username
      value: qiuguobin
    - name: password
      value: dckr_pat_DamamBGkd3L...
  taskRef:
    name: task-docker5
